-- AUTO-GENERATED by build-sites-seed.mjs — do not edit by hand.
-- Source: injection_sites.csv
-- Re-generate: node supabase/sites/build-sites-seed.mjs
-- Idempotent: ON CONFLICT (id) DO UPDATE keeps re-seeds clean.
-- Requires migration 001_injection_site_catalogue.sql (the table) first.

-- ===== injection_sites (read-only catalogue) =====
INSERT INTO injection_sites (id, label, route, side, aspect, x, y, sort_order) VALUES
  ('im-glute-r', 'Glute – Right', 'im'::admin_route, 'right', 'posterior', 54.9, 49.5, 1),
  ('im-glute-l', 'Glute – Left', 'im'::admin_route, 'left', 'posterior', 44.9, 49.5, 2),
  ('im-delt-r', 'Delt – Right', 'im'::admin_route, 'right', 'anterior', 62.6, 21.5, 3),
  ('im-delt-l', 'Delt – Left', 'im'::admin_route, 'left', 'anterior', 37.4, 21.5, 4),
  ('im-quad-out-r', 'Outer Quad – Right', 'im'::admin_route, 'right', 'anterior', 61, 58, 5),
  ('im-quad-out-l', 'Outer Quad – Left', 'im'::admin_route, 'left', 'anterior', 39, 58, 6),
  ('im-quad-front-r', 'Front Quad – Right', 'im'::admin_route, 'right', 'anterior', 54.5, 64, 7),
  ('im-quad-front-l', 'Front Quad – Left', 'im'::admin_route, 'left', 'anterior', 45.5, 64, 8),
  ('im-bicep-r', 'Bicep – Right', 'im'::admin_route, 'right', 'anterior', 63.1, 31.9, 9),
  ('im-bicep-l', 'Bicep – Left', 'im'::admin_route, 'left', 'anterior', 36.9, 31.9, 10),
  ('im-tricep-r', 'Tricep – Right', 'im'::admin_route, 'right', 'posterior', 66, 31, 11),
  ('im-tricep-l', 'Tricep – Left', 'im'::admin_route, 'left', 'posterior', 34, 31, 12),
  ('im-lat-r', 'Lat – Right', 'im'::admin_route, 'right', 'posterior', 57.5, 35.5, 13),
  ('im-lat-l', 'Lat – Left', 'im'::admin_route, 'left', 'posterior', 42.5, 35.5, 14),
  ('im-pec-r', 'Pec – Right', 'im'::admin_route, 'right', 'anterior', 55.4, 24.8, 15),
  ('im-pec-l', 'Pec – Left', 'im'::admin_route, 'left', 'anterior', 44.8, 24.8, 16),
  ('im-calf-r', 'Calf – Right', 'im'::admin_route, 'right', 'posterior', 57.1, 76.7, 17),
  ('im-calf-l', 'Calf – Left', 'im'::admin_route, 'left', 'posterior', 42.8, 76.9, 18),
  ('sq-abdo-lr', 'Lower Abdomen – Right', 'subq'::admin_route, 'right', 'anterior', 54.8, 48.4, 19),
  ('sq-abdo-ll', 'Lower Abdomen – Left', 'subq'::admin_route, 'left', 'anterior', 45.2, 48.4, 20),
  ('sq-abdo-r', 'Side Abdomen – Right', 'subq'::admin_route, 'right', 'anterior', 56, 40.1, 21),
  ('sq-abdo-l', 'Side Abdomen – Left', 'subq'::admin_route, 'left', 'anterior', 44.2, 40.1, 22),
  ('sq-flank-r', 'Love Handle – Right', 'subq'::admin_route, 'right', 'posterior', 56.9, 43, 23),
  ('sq-flank-l', 'Love Handle – Left', 'subq'::admin_route, 'left', 'posterior', 42.7, 43.1, 24),
  ('sq-glute-r', 'Glute – Right', 'subq'::admin_route, 'right', 'posterior', 54.9, 52.6, 25),
  ('sq-glute-l', 'Glute – Left', 'subq'::admin_route, 'left', 'posterior', 44.8, 52.6, 26),
  ('sq-thigh-up-r', 'Outer Thigh – Upper Right', 'subq'::admin_route, 'right', 'anterior', 59.2, 54.1, 27),
  ('sq-thigh-up-l', 'Outer Thigh – Upper Left', 'subq'::admin_route, 'left', 'anterior', 40.7, 54.1, 28),
  ('sq-thigh-lo-r', 'Outer Thigh – Lower Right', 'subq'::admin_route, 'right', 'anterior', 58.9, 67.2, 29),
  ('sq-thigh-lo-l', 'Outer Thigh – Lower Left', 'subq'::admin_route, 'left', 'anterior', 41, 67.2, 30),
  ('sq-arm-r', 'Back of Arm – Right', 'subq'::admin_route, 'right', 'posterior', 64.1, 33.2, 31),
  ('sq-arm-l', 'Back of Arm – Left', 'subq'::admin_route, 'left', 'posterior', 35.8, 33.1, 32),
  ('im-vglute-r', 'Ventroglute – Right', 'im'::admin_route, 'right', 'anterior', 58.6, 48.6, 33),
  ('im-vglute-l', 'Ventroglute – Left', 'im'::admin_route, 'left', 'anterior', 41.4, 48.6, 34),
  ('im-trap-r', 'Trap – Right', 'im'::admin_route, 'right', 'posterior', 54.6, 22.1, 35),
  ('im-trap-l', 'Trap – Left', 'im'::admin_route, 'left', 'posterior', 45.2, 22, 36)
ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label,
  route = EXCLUDED.route,
  side = EXCLUDED.side,
  aspect = EXCLUDED.aspect,
  x = EXCLUDED.x,
  y = EXCLUDED.y,
  sort_order = EXCLUDED.sort_order;
