-- ============================================================
--  ONE SUBSCRIPTION PER USER, EVER. The per-user lease `startTrial` holds while
--  it checks Stripe and creates.
--  Migration: `trial_start_lease`
--
--  ✅ APPLIED by Adrian, 2026-08-14, and VERIFIED the same day against the live
--  Data API with the service key: `billing_customers?select=trial_lock_until`
--  returns 200 (it returned 400 before), and the count of rows with
--  `trial_lock_until > now()` is ZERO, which is what a correct backfill to
--  '-infinity' looks like.
--
--  A hand-applied migration never appears in `list_migrations`, so this header
--  is a CLAIM and never a record. VERIFY AGAINST THE LIVE SCHEMA:
--
--    select column_name, data_type, is_nullable, column_default
--    from information_schema.columns
--    where table_schema = 'public'
--      and table_name = 'billing_customers'
--      and column_name = 'trial_lock_until';
--
--  Expected after applying: one row, `timestamp with time zone`, NO, '-infinity'.
-- ============================================================
--
--  THE DEFECT, DRIVEN AND MEASURED (cold review, 2026-08-12)
--    `startTrial`'s duplicate guard is a READ of Stripe followed by a WRITE to
--    Stripe, and the only thing serialising it was an idempotency key of
--    `trial:${user.id}:${plan}`. **Two plans are two keys.** Two concurrent
--    calls from one signed-in user therefore both read "nothing live here" and
--    both created: ONE USER, TWO LIVE TRIALS, both billable.
--
--    Everything downstream then took `limit(1)` off the mirror, so Cancel
--    stopped the wrong one, returned `{ok: true}`, and a Stripe test clock
--    rolled to day 8 and took $69.99 from somebody who had pressed Cancel and
--    been told in writing they would not be charged.
--
--    The cancel path was repaired at its own end (it asks Stripe and stops ALL
--    of them). This closes the source.
--
--  WHY A LEASE COLUMN AND NOT `pg_advisory_lock`
--    An advisory lock is the textbook answer and it cannot work over this stack.
--    Both flavours fail, for opposite reasons:
--
--      - `pg_advisory_lock` is SESSION-scoped. Every statement here goes through
--        PostgREST, which serves requests from a CONNECTION POOL, so the lock
--        would be held on whichever backend happened to serve the acquire and
--        the release would arrive on a different one. `pg_advisory_unlock` only
--        works from the owning session, so the lock would leak permanently and
--        every later trial start for that user would block forever.
--      - `pg_try_advisory_xact_lock` is TRANSACTION-scoped and PostgREST runs
--        each request in its own transaction, so it would be released the
--        instant the RPC returned — before the Stripe call it exists to guard.
--
--    The thing being protected is an HTTP call to Stripe, which no Postgres lock
--    can span. A lease with a TTL can: it is claimed by a conditional UPDATE
--    (atomic, one statement), it survives the Stripe round-trip, and it CANNOT
--    leak, because it expires. A crashed request costs the next one 90 seconds
--    rather than locking the account out for good.
--
--    This is the same claim-before-act shape `lib/notifications/runner.ts`
--    already uses for the trial reminder, where a conditional UPDATE's row count
--    decides who owns the send. It is proven on this codebase.
--
--  WHY IT LIVES ON `billing_customers`
--    Exactly one row per user, created before any subscription can exist
--    (`findOrCreateCustomer` runs first, and that ordering is what guarantees
--    there is always a row to claim). Service-role-write only, already. A
--    separate lock table would be a second thing to keep in step with the user
--    lifecycle for no gain, and it would not cascade on account deletion the way
--    this does.
--
--  WHY `-infinity` AND NOT NULL
--    So the claim is a single `<` comparison with no NULL branch. `default now()`
--    was rejected: the row is inserted by Postgres's clock and the claim compares
--    against Node's, so clock skew of a few milliseconds would make the very
--    first trial start report "busy" on a lease nobody holds. `-infinity` is
--    always in the past on every clock there is.
--
--  ⚠️ WHAT THE CODE DOES WHILE THIS IS UNAPPLIED
--    It PROCEEDS WITHOUT THE LEASE and logs, rather than refusing to start
--    trials. That is deliberate and it is the same call `notifications/004`
--    made: an unapplied migration must not take a payment path down.
--
--    The hole is not left open in the meantime. `startTrial` re-lists Stripe
--    after creating and, if the customer somehow holds more than one live
--    subscription, cancels every one but the oldest — a rule both racers compute
--    identically, so they converge on the same survivor. The lease makes that
--    reconciliation unreachable; without the lease it is what closes the race.
--
--  NO GRANT IS NEEDED
--    `001` grants table-level SELECT on `billing_customers` to `authenticated`,
--    and a table-level grant covers columns added later. This is deliberately
--    NOT the column-level shape `grants/003`/`004` use on `profiles`: those
--    ENUMERATE, so every new column there needs adding to the list or a
--    legitimate write starts failing with 42501. That maintenance trap has
--    already bitten `profiles` twice and is not being reproduced here.
--
--    The value is not sensitive. It is "a trial start is in progress", which the
--    user performing it already knows.
-- ============================================================

alter table public.billing_customers
  add column if not exists trial_lock_until timestamptz not null
    default '-infinity'::timestamptz;

comment on column public.billing_customers.trial_lock_until is
  'Lease held by startTrial across its Stripe check-and-create. Claimed by a '
  'conditional UPDATE (see lib/billing/trialLease.ts), expires on its own so a '
  'crashed request cannot lock the account out. -infinity means unheld.';

-- ============================================================
--  VERIFY (paste and run; do not trust the header)
-- ============================================================
--
--  1. The column exists, is NOT NULL, and defaults to the distant past:
--
--     select column_name, data_type, is_nullable, column_default
--     from information_schema.columns
--     where table_schema = 'public'
--       and table_name = 'billing_customers'
--       and column_name = 'trial_lock_until';
--
--     -> trial_lock_until | timestamp with time zone | NO | '-infinity'::timestamp with time zone
--
--  2. Every existing row is unheld (this backfills to the default, so the count
--     of held leases must be ZERO immediately after applying):
--
--     select count(*) filter (where trial_lock_until > now()) as held,
--            count(*)                                        as rows
--     from public.billing_customers;
--
--     -> held = 0
--
--  3. The claim really is exclusive. Run twice in a row against any real row;
--     the FIRST returns 1 row and the SECOND returns 0:
--
--     update public.billing_customers
--     set trial_lock_until = now() + interval '90 seconds'
--     where user_id = '<some user id>'
--       and trial_lock_until < now()
--     returning user_id, trial_lock_until;
--
--     Then put it back, or wait 90 seconds:
--
--     update public.billing_customers
--     set trial_lock_until = '-infinity'
--     where user_id = '<the same user id>';
--
--  4. `authenticated` can still read the table and still cannot write it. With a
--     real user JWT and the publishable key:
--
--     GET   /rest/v1/billing_customers?select=*          -> 200, own row only
--     PATCH /rest/v1/billing_customers?user_id=eq.<self>
--           { "trial_lock_until": "-infinity" }          -> 403 42501
