"use client";

import Image from "next/image";

import { fit } from "@/lib/onboarding/fit";
import { cn } from "@/lib/utils";

/**
 * Kyle, wherever he stands (Spec 3-01 §3.3).
 *
 * ## Dropping the art in
 *
 * Nothing is hand-exported. The renders live in `scripts/brand/kyle/` and
 * `node scripts/brand/kyle.mjs` writes every slot below, plus the launch
 * images and the app icons. Drop new masters in, re-run it, look at the result.
 *
 *     kyle-wave.png     waving          -> the open of onboarding
 *     kyle-flex.png     flexing, happy  -> welcome, once the trial starts
 *     kyle-thumbs.png   thumbs up       -> the celebrate screen
 *     kyle-default.png  flexing, hard   -> the launch splash and the app icon
 *
 * Until a file is there, a designed placeholder renders instead of a broken
 * image, so a preview reads as "art goes here" rather than "this is broken".
 *
 * ## The art is cut out, and the mask that used to cover for that is gone
 *
 * The first renders arrived on a near-black backdrop, a few points of luminance
 * off Kyle's own black singlet — close enough that any automatic matte took the
 * singlet with the background and punched holes through his shirt. Rather than
 * cut him out, the image edge was FEATHERED with a radial mask so the backdrop
 * dissolved into our canvas.
 *
 * The art is a true transparent cutout now, so there is no backdrop to hide and
 * the mask is removed. That is not merely tidying: the old comment claimed the
 * mask was "harmless" on a transparent PNG, and that stopped being true the
 * moment the art was CROPPED to him. The mask went clear at 78% of the radius,
 * which on a tight crop is his fists — it would have quietly eaten both hands
 * and the top of his cap. If a future render ever comes back on a backdrop, cut
 * it out at the source rather than bringing this back.
 */

export type KylePose = "thumbs" | "flex" | "wave" | "default";

const KYLE_ART: Record<KylePose, string> = {
  thumbs: "/onboarding/kyle-thumbs.png",
  flex: "/onboarding/kyle-flex.png",
  wave: "/onboarding/kyle-wave.png",
  default: "/onboarding/kyle-default.png",
};

/** All four landed 2026-09-21 (Adrian) — the Trakabl singlet, as a placeholder
 *  until the mascot's own rebrand. Generated by `scripts/brand/kyle.mjs`. */
const ART_PRESENT: Record<KylePose, boolean> = {
  thumbs: true,
  flex: true,
  wave: true,
  default: true,
};

const POSE_LABEL: Record<KylePose, string> = {
  thumbs: "Kyle, thumbs up",
  flex: "Kyle, flexing",
  wave: "Kyle, waving",
  default: "Kyle, flexing",
};

/**
 * A soft amber bloom behind him, fading in once (Adrian, 2026-08-05: "add a
 * small amber bloom that fades in, and do that on the other Kyle stuff as
 * well").
 *
 * It belongs to KYLE rather than to a screen, which is why it lives here and
 * not in three call sites: he appears on celebrate, welcome and the greeting,
 * and a light that only reached one of them would read as that screen being
 * special rather than as him being lit.
 *
 * One-shot and behind him, so it is depth rather than ambient motion —
 * `ui-context.md` bans the latter. It is also the reason the mascot is wrapped
 * in a positioned span now: the bloom needs something to be absolute against.
 */
function Bloom({ extent }: { extent: string }) {
  return (
    <span
      aria-hidden
      className="animate-welcome-bloom pointer-events-none absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-full blur-2xl"
      style={{
        width: `calc(${extent} * 0.95)`,
        height: `calc(${extent} * 0.95)`,
        background:
          "radial-gradient(circle, color-mix(in srgb, var(--accent-amber) 26%, transparent), transparent 70%)",
      }}
    />
  );
}

export function Mascot({
  pose,
  size = 200,
  short,
  className,
  bloom = true,
}: {
  pose: KylePose;
  size?: number;
  /**
   * His height on an iPhone SE in Safari, where `size` is the height on a tall
   * phone. See `lib/onboarding/fit.ts`.
   *
   * Kyle is the tallest thing on every screen he stands on and the one thing on
   * it that is not a sentence, so he is what a short phone takes its room back
   * from. Before this, the SE kept him at full height and slid the answer ticks
   * on celebrate underneath the button instead. Omit it and he is `size` on
   * every phone.
   */
  short?: number;
  className?: string;
  /** Set false where a screen supplies its own light (the effect harness). */
  bloom?: boolean;
}) {
  const extent = short === undefined ? `${size}px` : fit(size, short);

  if (ART_PRESENT[pose]) {
    return (
      <span className="relative inline-flex items-center justify-center">
        {bloom ? <Bloom extent={extent} /> : null}
        <Image
        src={KYLE_ART[pose]}
        alt={POSE_LABEL[pose]}
        /* The art's real pixels. Cropped to one box shared by every pose, so
           this is the same for all four — see scripts/brand/kyle.mjs. */
        width={1018}
        height={900}
        priority
        sizes="(max-width: 480px) 60vw, 260px"
          className={cn(
            "animate-kyle relative h-auto w-auto object-contain",
            className,
          )}
          style={{ maxHeight: extent }}
        />
      </span>
    );
  }

  return (
    <div
      className={cn(
        "flow-card flex flex-col items-center justify-center gap-3 rounded-2xl bg-bg-surface",
        className,
      )}
      style={{ height: size, width: size * 0.78 }}
      role="img"
      aria-label={POSE_LABEL[pose]}
    >
      <svg
        viewBox="0 0 60 96"
        width={size * 0.34}
        height={size * 0.54}
        aria-hidden
        className="text-text-subtle"
      >
        <rect x="19" y="2" width="22" height="13" rx="2.5" fill="currentColor" opacity="0.35" />
        <rect x="21.5" y="13" width="17" height="5" rx="1" fill="currentColor" opacity="0.5" />
        <rect
          x="14"
          y="17"
          width="32"
          height="72"
          rx="5"
          fill="none"
          stroke="currentColor"
          strokeWidth="1"
          strokeDasharray="3 3"
        />
      </svg>
      <p className="text-[9px] font-sans uppercase tracking-[0.18em] text-text-subtle">
        Kyle · {pose}
      </p>
    </div>
  );
}
